# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_yodlee
# 
# Translators:
# Yenthe Van Ginneken <yenthespam@gmail.com>, 2016
# Erwin van der Ploeg <erwin@odooexperts.nl>, 2016
# Cas Vissers <casvissers@brahoo.nl>, 2016
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 10.0+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-11-03 13:22+0000\n"
"PO-Revision-Date: 2016-11-03 13:22+0000\n"
"Last-Translator: Cas Vissers <casvissers@brahoo.nl>, 2016\n"
"Language-Team: Dutch (https://www.transifex.com/odoo/teams/41243/nl/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: nl\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:102
#: code:addons/account_yodlee/models/yodlee.py:107
#, python-format
msgid "(Diagnostic: %r for URL %s)"
msgstr "(Diagnose: %r voor URL %s)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:406
#, python-format
msgid ""
"Account Already Registered (436):Your Auto-Registration could not be "
"completed because the site reports that your account is already registered."
"  Please log in to the site to confirm and then complete the site addition "
"process with the correct login information."
msgstr ""
"Rekening reeds geregistreerd (436): Uw auto-registratie kan niet worden "
"voltooid omdat de site meldt dat uw account al is geregistreerd. Gelieve in "
"te loggen op de site om te bevestigen en vervolgens het site toevoeging "
"proces invullen met de juiste gegevens."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:393
#, python-format
msgid ""
"Account Locked (407): We could not update your account because it appears "
"your account has been locked. This usually results from too many "
"unsuccessful login attempts in a short period of time. Please visit the site"
" or contact its customer support to resolve this issue.  Once done, please "
"update your account credentials in case they are changed."
msgstr ""
"Rekening geblokkeerd(407): Wij kunnen uw account niet bijwerken omdat het "
"lijkt dat u account is geblokkeerd. Dit ontstaat vaak door teveel mislukte "
"aanmeldingspogingen in een korte tijd. Ga naar de site of neem contact op "
"customer support om dit probleem op te lossen. Eenmaal gedaan, werk uw "
"accountgegevens bij in het geval dat deze zijn gewijzigd."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:420
#, python-format
msgid ""
"Account Not Found(408): We're sorry, we couldn't find any accounts for you "
"at the site. Please log in at the site and confirm that your account is set "
"up, then try again."
msgstr ""
"Rekening niet gevonden (408): Het spijt ons, we konden we geen rekening voor"
" u vinden op de site. Gelieve in te loggen op de site en bevestigen dat uw "
"account correct is ingesteld en probeer het opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:398
#, python-format
msgid ""
"Account Reported Closed (422): We were unable to update your account "
"information because it appears one or more of your related accounts have "
"been closed.  Please deactivate or delete the relevant account and try "
"again."
msgstr ""
"Rekening gerapporteerd als gesloten (422): We waren niet in staat om uw "
"account bij te werken omdat het lijkt een of meer van uw gerelateerde "
"accounts zijn afgesloten. Gelieve uit te schakelen of de betreffende account"
" te verwijderen en probeer het opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:395
#, python-format
msgid ""
"Account Type Not Supported(417):The type of account we found is not "
"currently supported.  Please remove this site and add as a  manual account."
msgstr ""
"Rekening type niet ondersteund (417): Het gevonden rekening type is "
"momenteel niet ondersteund. Verwijder deze site en voeg toe als handmatige "
"rekening."

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_journal_yodlee_account_status
msgid "Active/Inactive on Yodlee system"
msgstr "Actief/inactief op Yodlee systeem"

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_provider_yodlee_additional_status
msgid "Additional information on status"
msgstr "Aanvullende informatie over de status"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:424
#, python-format
msgid "An Error has occurred (code %s)"
msgstr "Er heeft zich een fout voorgedaan  (code %s)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:309
#: code:addons/account_yodlee/models/yodlee.py:311
#, python-format
msgid ""
"An error has occurred while trying to refresh accounts (type not supported)"
msgstr ""
"Er is een fout opgetreden bij het ophalen van de rekening (type wordt niet "
"ondersteund)"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_res_company
msgid "Companies"
msgstr "Bedrijven"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:159
#, python-format
msgid "Could not retrieve login form for siteId: %s (%s)"
msgstr "Kan inlogformulier niet ophalen van siteId: %s (%s)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:390
#, python-format
msgid ""
"Credential Re-Verification Required (402): We could not update your account "
"because your username and/or password were reported to be incorrect.  Please"
" re-verify your username and password."
msgstr ""
"Wachtwoord re-verificatie vereist (402): Wij kunnen uw account niet "
"bijwerken omdat uw gebruikersnaam en/of wachtwoord onjuist zijn. Gelieve "
"opnieuw te controleren."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:396
#, python-format
msgid ""
"Credential Re-Verification Required (420):The site has merged with another. "
"Please re-verify your credentials at the site and update the same."
msgstr ""
"Wachtwoord re-verificatie vereist (420): De site is gefuseerd met een "
"andere. Gelieve controleer uw referenties op de site en het actualiseer "
"deze."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:307
#, python-format
msgid ""
"Different error have occurred on different accounts, see provider account "
"message for details"
msgstr ""
"Verschillende fouten opgetreden op verschillende rekeningen, zie provider "
"berichten voor meer informatie"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:101
#, python-format
msgid "Error %s, message: %s, reference code: %s"
msgstr "Fout %s, bericht: %s, referentie code: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:389
#, python-format
msgid ""
"Home Value Not Found (511): The site is unable to provide home value for "
"your property. We suggest you to delete this site."
msgstr ""
"Home waarde niet gevonden (511): De site is niet in staat om een home waarde"
" aan te bieden voor uw eigenschap. Wij raden u aan om deze site te "
"verwijderen."

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_journal
msgid "Interface for online account journal"
msgstr "Interface voor online rekening dagboek"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:397
#, python-format
msgid ""
"Invalid Language Setting (421): The language setting for your site account "
"is not English. Please visit the site and change the language setting to "
"English."
msgstr ""
"Ongeldige taalinstelling (421): De taalinstelling voor uw site account is "
"niet Engels. Ga naar de site en wijzig de taalinstelling in Engels."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:412
#, python-format
msgid ""
"MFA error: Additional Authentication Enrollment Required (521) : Please "
"enroll in the new security authentication system, <Account Name> has "
"introduced. Ensure your account settings in <Cobrand> are updated with this "
"information."
msgstr ""
"MFA fout: Extra authenticatie Inschrijving vereist (521): Gelieve in te "
"schrijven in het nieuwe beveiliging authenticatie systeem,  welke <Account "
"Name>  heeft ge√Øntroduceerd. Zorg ervoor dat uw accountinstellingen in "
"<Cobrand> > zijn bijgewerkt met deze informatie."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:415
#, python-format
msgid ""
"MFA error: Authentication Information Expired (524):We're sorry, the "
"authentication information you provided has expired. Please try again."
msgstr ""
"MFA fout: Authenticatie informatie verlopen (524): Het spijt ons, de "
"authenticatie-informatie die u verstrekt heeft is verlopen. Probeer het "
"opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:411
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (520):We're sorry, the site "
"indicates that the additional authentication information you provided is "
"incorrect. Please try updating your account again."
msgstr ""
"MFA fout: Authentificatie informatie onjuist (520): Het spijt ons, de site "
"geeft aan dat de extra authenticatie door u verstrekt heeft onjuist is. "
"Probeer het bijwerken van uw account opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:414
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (523):We're sorry, the "
"authentication information you  provided is incorrect. Please try again."
msgstr ""
"MFA fout: Authentificatie informatie onjuist (523): Het spijt ons, de "
"authenticatie-informatie die u heeft opgegeven is onjuist. Probeer het "
"opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:410
#, python-format
msgid ""
"MFA error: Authentication Information Required (519): Your account was not "
"updated as your authentication information like security question and answer"
" was unavailable or incomplete. Please update your account settings."
msgstr ""
"MFA fout: Authenticatie informatie vereist (519): Je rekening is niet "
"bijgewerkt omdat uw verificatie-informatie zoals geheime vraag en antwoord "
"niet beschikbaar of onvolledig zijn. Werk uw accountinstellingen bij."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:409
#, python-format
msgid ""
"MFA error: Authentication Information Unavailable (518):Your account was not"
" updated as the required additional authentication information was "
"unavailable. Please try now."
msgstr ""
"MFA fout: Authentificatie informatie niet beschikbaar (518): Je account is "
"niet bijgewerkt omdat de vereiste bijkomende verificatie informatie niet "
"beschikbaar was. Probeer nu aub."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:416
#, python-format
msgid ""
"MFA error: Credential Re-Verification Required (526): We could not update "
"your account because your username/password or additional security "
"credentials are incorrect. Please try again."
msgstr ""
"MFA fout: Inlog gegevens re-verificatie vereist (526): Wij kunnen uw account"
" niet bij werken omdat uw gebruikersnaam en/of wachtwoord of extra "
"beveiliging referenties onjuist zijn. Probeer het opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:427
#, python-format
msgid ""
"MFA error: Problem Updating Account (525): We could not update your account "
"for technical reasons. This type of error is usually resolved in a few days."
" We apologize for the inconvenience. Please try again later."
msgstr ""
"MFA fout: Probleem met updaten rekening (525): Wij kunnen uw account niet "
"bijwerken om technische redenen. Dit type fout wordt meestal opgelost in een"
" paar dagen. Onze excuses voor het ongemak. Probeer het later opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:413
#, python-format
msgid ""
"MFA error: Request Timed Out (522) :Your request has timed out as the "
"required security information was unavailable or was not provided within the"
" expected time. Please try again."
msgstr ""
"MFA fout: Time-out (522): Uw aanvraag is verlopen omdat de vereiste "
"informatie over de beveiliging niet beschikbaar was of niet ontvangen is "
"binnen de verwachte tijd. Probeer het opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:425
#, python-format
msgid ""
"MFA error: Site Device Information Expired(509): We're sorry, we can't "
"update your account because your token is no longer valid at the site. "
"Please update your information and try again, or contact customer support."
msgstr ""
"MFA fout: Site apparaat informatie verlopen (509): Het spijt ons, we kunnen "
"uw rekening niet bijwerken omdat uw token is niet langer geldig is op de "
"site. Werkt uw gegevens bij en probeer het opnieuw, of neem contact op met "
"de klantenservice."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:381
#, python-format
msgid ""
"Multiple User Logins(416): We attempted to update your account, but another "
"session was already established at the same time.  If you are currently "
"logged on to this account directly, please log off and try after some time"
msgstr ""
"Meerdere gebruiker logins (416): We hebben geprobeerd om uw account bij te "
"werken, maar een andere sessie werd op hetzelfde moment gemaakt. Als u op "
"dit moment rechtstreeks bent aangemeld bij dit account, dan kunt u zich "
"afmelden en het opnieuw proberen na enige tijd"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:407
#, python-format
msgid ""
"New Login Information Required(506):We're sorry, to log in to this site, you"
" need to provide additional information. Please update your account and try "
"again."
msgstr ""
"Nieuw inlog gegevens nodig(506): Sorry, om in te loggen op deze site, moet u"
" aanvullende informatie te verstrekken. Werk u uw account bij en probeer het"
" opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:383
#, python-format
msgid ""
"No Account Found (423): We were unable to detect an account. Please verify "
"that you account information is available at this time and If the problem "
"persists, please contact customer support at online@odoo.com for further "
"assistance."
msgstr ""
"Geen rekening gevonden (423): We waren niet in staat om een account te "
"vinden. Controleer of de account informatie beschikbaar is en ofhet probleem"
" aanhoudt, neem dan contact op met de klantenservice of online@odoo.com voor"
" verdere assistentie."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:408
#, python-format
msgid ""
"No Payees Found(512):Your request cannot be completed as no payees were "
"found in your account."
msgstr ""
"Geen incassanten gevonden (512): Uw aanvraag kan niet worden voltooid omdat "
"er geen betalingen werden gevonden in uw account."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:48
#, python-format
msgid "Please configure an email in the company settings."
msgstr "Configureer a.u.b een e-mail onder de bedrijfsinstellingen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:144
#, python-format
msgid "Please enter at least 3 characters for the search"
msgstr "Type tenminste 3 karakter voor de zoekopdracht"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:190
#, python-format
msgid "Please fill all required fields"
msgstr "U moet alle verplichte velden invullen"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:392
#, python-format
msgid ""
"Problem Updating Account (406): We could not update your account because the"
" site requires you to perform some additional action. Please visit the site "
"or contact its customer support to resolve this issue. Once done, please "
"update your account credentials in case they are changed else try again."
msgstr ""
"Probleem met updaten rekening (406): Wij kunnen uw account niet bijwerken "
"omdat de site vereist dat u extra acties uitvoert. Ga naar de site of neem "
"contact op met de customer support om dit probleem op te lossen. Eenmaal "
"gedaan, werk uw accountgegevens bij in het geval dat ze zijn gewijzigd en "
"probeer het opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:426
#, python-format
msgid ""
"Problem Updating Account (517) :We'resorry, there was a technical problem "
"updating your account. Please try again."
msgstr ""
"Probleem met updaten rekening(517): Sorry, er was een technisch probleem met"
" het bijwerken van uw account. Probeer het opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:417
#, python-format
msgid ""
"Problem Updating Account(401):We're sorry, your request timed out. Please "
"try again."
msgstr ""
"Probleem met bijwerken rekening (401): Sorry, uw verzoek heeft geresulteerd "
"in een time-out. Probeer het opnieuw"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:418
#, python-format
msgid ""
"Problem Updating Account(403):We're sorry, there was a technical problem "
"updating your account. This kind of error is usually resolved in a few days."
" Please try again later."
msgstr ""
"Probleem met bijwerken rekening(403): Sorry, er was een technisch probleem "
"met het bijwerken van uw account. Dit soort fout wordt meestal opgelost in "
"een paar dagen. Probeer het later opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:419
#, python-format
msgid ""
"Problem Updating Account(404):We're sorry, there was a technical problem "
"updating your account. Please try again later."
msgstr ""
"Probleem bijwerken rekening(404): Sorry, was er een technisch probleem met "
"het bijwerken van uw account. Probeer het later opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:377
#, python-format
msgid ""
"Problem Updating Account(409): We could not update your account because the "
"end site is experiencing technical difficulties."
msgstr ""
"Probleem met bijwerken rekening(409): Wij kunnen uw account niet bijwerken "
"omdat de externe website kampt met technische problemen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:379
#, python-format
msgid ""
"Problem Updating Account(412): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Probleem met het updaten van uw account (412): We konden uw account niet "
"updaten omdat de website technische problemen ondervind."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:421
#, python-format
msgid ""
"Problem Updating Account(413):We're sorry, we couldn't update your account "
"at the site because of a technical issue. This type of problem is usually "
"resolved in a few days. Please try again later."
msgstr ""
"Probleem met bijwerken rekening (413): Sorry, we konden uw account op de "
"site niet bij werken als gevolg van een technisch probleem. Dit type "
"probleem wordt gewoonlijk opgelost in een paar dagen. Probeer het later "
"opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:380
#, python-format
msgid ""
"Problem Updating Account(415): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Probleem met bijwerken rekening(415): Wij kunnen uw account niet bijwerken "
"omdat de site kampt met technische problemen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:382
#, python-format
msgid ""
"Problem Updating Account(418): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Probleem met bijwerken rekening (418): Wij kunnen uw account niet bijwerken "
"omdat de site kampt met technische problemen. Probeer het later opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:422
#, python-format
msgid ""
"Problem Updating Account(419):We're sorry, we couldn't update your account "
"because of unexpected variations at the site. This kind of problem is "
"usually resolved in a few days. Please try again later."
msgstr ""
"Probleem met bijwerken rekening (419): Sorry, we konden uw rekening niet bij"
" werken als gevolg van onverwachte variaties op de site. Dit soort problemen"
" wordt meestal opgelost in een paar dagen. Probeer het later opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:385
#, python-format
msgid ""
"Problem Updating Account(425): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Probleem met bijwerken rekening (425): Wij kunnen uw account niet bijwerken "
"omdat de site kampt met technische problemen. Probeer het later opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:386
#, python-format
msgid ""
"Problem Updating Account(426): We could not update your account for "
"technical reasons. This type of error is usually resolved in a few days. We "
"apologize for the inconvenience."
msgstr ""
"Probleem met bijwerken rekening (426): Wij kunnen uw account niet bijwerken "
"omdat de site kampt met technische problemen. Dit type fout wordt meestal "
"opgelost in een paar dagen. Onze excuses voor het ongemak. Probeer het later"
" opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:423
#, python-format
msgid ""
"Problem Updating Account(507):We're sorry, Yodlee has just started providing"
" data updates for this site, and it may take a few days to be successful as "
"we get started. Please try again later."
msgstr ""
"Probleem met bijwerken rekening (507): Sorry, Yodlee is net begonnen met het"
" verstrekken van data updates voor deze website, het kan een paar dagen "
"duren om dit op te lossen. Probeer het later opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:388
#, python-format
msgid ""
"Property Record Not Found (510): The site is unable to find any property "
"information for your address. Please verify if the property address you have"
" provided is correct."
msgstr ""
"Property record niet gevonden (510): De site is niet in staat om eigendom "
"informatie voor uw adres te vinden. Controleer of het eigendom dat u voor uw"
" adres verstrekt hebt correct is."

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "Provider for online rekening synchronisatie"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:401
#, python-format
msgid ""
"Re-Verification Required (429): We could not update your account due to the "
"site requiring you to verify your personal information. Please log in to the"
" site and update the fields required."
msgstr ""
"Re-verificatie vereist (429): Wij kunnen uw account niet bijwerken als "
"gevolg van de site die u uw persoonlijke gegevens wil verifi√´ren. Gelieve in"
" te loggen op de site en de verplichte velden invullen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:399
#, python-format
msgid ""
"Re-verification Required (427): We could not update your account due to the "
"site requiring you to view a new promotion. Please log in to the site and "
"click through to your account overview page to update the account.  We "
"apologize for the inconvenience."
msgstr ""
"Re-verificatie vereist (427): Wij kunnen uw account niet bijwerken omdat de "
"website u verlangt te kijken naar een nieuwe promotie. Gelieve in te loggen "
"op de website en daar uw account overzicht pagina om het account bij te "
"werken. Onze excuses voor het ongemak."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:400
#, python-format
msgid ""
"Re-verification Required (428): We could not update your account due to the "
"site requiring you to accept a new Terms & Conditions. Please log in to the "
"site and read and accept the T&C."
msgstr ""
"Re-verificatie vereist (428): Wij kunnen uw account niet bijwerken als "
"gevolg van de site die wilt dat u nieuwe voorwaarden accepteert. Gelieve in "
"te loggen op de website  een daar de algemene voorwaarden lezen en "
"accepteren."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:403
#, python-format
msgid ""
"Registration Requires Attention (433): Auto registration is not complete. "
"Please complete your registration at the end site. Once completed, please "
"complete adding this account."
msgstr ""
"Inschrijving vereist aandacht (433): Automatische registratie is niet "
"voltooid. Vul uw registratie in op het einde van de website. Eenmaal "
"voltooid, vul dan dit account compleet in."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:404
#, python-format
msgid ""
"Registration Requires Attention (434): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"Inschrijving vereist aandacht (434): Uw auto-registratie kan niet worden "
"voltooid en vereist verdere input. Controleer opnieuw uw registratie-"
"informatie om het proces te voltooien."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:405
#, python-format
msgid ""
"Registration Requires Attention (435): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"Inschrijving vereist aandacht (435): Uw auto-registratie kan niet worden "
"voltooid en vereist verdere input. Controleer opnieuw uw registratie-"
"informatie om het proces te voltooien."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:424
#, python-format
msgid ""
"Request Timed Out (508): We are sorry, your request timed out due to "
"technical reasons. Please try again."
msgstr ""
"Aanvraag time out (508): Het spijt ons, uw aanvraag heeft een time-out "
"gegeven om technische redenen. Probeer het opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:394
#, python-format
msgid ""
"Requested Account Type Not Found (414): We could not find your requested "
"account. You may have selected a similar site under a different category by "
"accident in which case you should select the correct site."
msgstr ""
"Gevraagde rekening type niet gevonden (414): We kunnen uw aangevraagde "
"rekening niet vinden. U kunt een soortgelijke site uit een andere categorie "
"per ongeluk, gekozen hebben, in welk geval u de juiste site moet selecteren."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:384
#, python-format
msgid ""
"Site Down for Maintenance(424):We were unable to update your account as the "
"site is temporarily down for maintenance. We apologize for the "
"inconvenience.  This problem is typically resolved in a few hours. Please "
"try later."
msgstr ""
"Site is in onderhoud (424): We waren niet in staat om uw account bij te "
"werken aangezien de site momenteel in onderhoud is. Onze excuses voor het "
"ongemak. Dit probleem wordt gewoonlijk opgelost in een paar uur. Probeer het"
" later alstublieft opnieuw."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:378
#, python-format
msgid ""
"Site No Longer Available (411):The site no longer provides online services "
"to its customers.  Please delete this account."
msgstr ""
"Site niet meer beschikbaar (411): De site biedt geen online diensten meer "
"aan haar klanten. Verwijder dit account."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:402
#, python-format
msgid ""
"Site No Longer Supported (430):This site is no longer supported for data "
"updates. Please deactivate or delete your account. We apologize for the "
"inconvenience."
msgstr ""
"Site niet meer ondersteund (430): Deze site wordt niet meer ondersteund voor"
" data updates. Gelieve te deactiveren of verwijder uw account. Onze excuses "
"voor het ongemak."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:387
#, python-format
msgid ""
"Site Not Supported (505): We currently does not support the security system "
"used by this site. We apologize for any inconvenience. Check back "
"periodically if this situation has changed."
msgstr ""
"Site niet ondersteund (505): Op dit moment ondersteunen we het beveiliging "
"systeem welke gebruikt wordt door deze site niet. We verontschuldigen ons "
"voor het ongemak. Controleer regelmatig of deze situatie is veranderd."

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_provider_yodlee_next_schedule_refresh
msgid "Technical field: scheduled time for yodlee to perform an update"
msgstr "Technisch veld: geplande tijd voor yodlee om een update uit te voeren"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:266
#: code:addons/account_yodlee/models/yodlee.py:267
#, python-format
msgid "Timeout: Could not retrieve accounts informations"
msgstr "Timeout: Kon geen account informatie ontvangen"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:53
#: code:addons/account_yodlee/models/yodlee.py:66
#: code:addons/account_yodlee/models/yodlee.py:79
#: code:addons/account_yodlee/models/yodlee.py:128
#, python-format
msgid "Timeout: the server did not reply within 30s"
msgstr "Timeout: De server heeft niet binnen 30s gereageerd."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:387
#, python-format
msgid ""
"Update Request Canceled(405):Your account was not updated because you "
"canceled the request."
msgstr ""
"Update aanvraag geannuleerd (405): Je account is niet bijgewerkt, omdat u "
"het verzoek heeft geannuleerd."

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company_yodlee_user_access_token
msgid "Yodlee access token"
msgstr "Yodlee toegangstoken"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal_yodlee_account_status
msgid "Yodlee account status"
msgstr "Yodlee account status"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider_yodlee_additional_status
msgid "Yodlee additional status"
msgstr "Yodlee bijkomende status"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider_yodlee_last_attempted_refresh
msgid "Yodlee last attempted refresh"
msgstr "Yodlee laatste ververspoging"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company_yodlee_user_login
msgid "Yodlee login"
msgstr "Yodlee login"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider_yodlee_next_schedule_refresh
msgid "Yodlee next schedule refresh"
msgstr "Yodlee volgende geplande verversing"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company_yodlee_user_password
msgid "Yodlee password"
msgstr "Yodlee wachtwoord"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal_yodlee_status_code
msgid "Yodlee status code"
msgstr "Yodlee status code"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company_yodlee_access_token
msgid "access_token"
msgstr "access_token"
